services:
  accbank-api:
    image: accbank-api
    environment:
      spring.profiles.active: docker
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: accbankdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s
